In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [37]:
from __future__ import print_function
import torch
import numpy as np

Pay attention that there is slight difference in syntax between NumPy and PyTorch.

When it comes to initializing tensor/ndarray, the biggest difference is that

- Most NumPy methods takes a tuple as the argument
- PyTorch takes an unpacked tuple as the argument

Observe the difference in the examples below:

Construct a 5x3 matrix, uninitialized:

In [38]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  2.0000e+00,  2.1007e-22],
        [-1.5849e+29,  4.0927e-11,  7.1450e+31],
        [ 4.1418e-41,  0.0000e+00,  2.1007e-22],
        [-8.5920e+09,  2.7474e-22, -1.5849e+29],
        [ 2.8026e-45,  0.0000e+00,  2.1007e-22]])


In [39]:
np.empty((5, 3))

array([[-1.04336503,  0.29767695,  0.45528051],
       [-0.48804965,  1.51569486, -1.92924095],
       [-1.18081524, -1.76143773,  1.26234469],
       [ 0.46067763, -1.09306842,  1.57190373],
       [ 1.60693347, -0.48680671, -1.00447347]])

Construct a randomly initialized matrix with each element from a uniform distribution
on the interval $[0, 1)$

In [40]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3321, 0.0214, 0.2379],
        [0.5233, 0.0557, 0.3155],
        [0.6148, 0.3346, 0.3737],
        [0.4859, 0.4904, 0.8262],
        [0.3149, 0.4305, 0.5864]])


Its most commonly used counterpart in NumPy is

In [41]:
np.random.rand(5, 3)

array([[0.35745212, 0.97718722, 0.35827868],
       [0.74037879, 0.58114691, 0.49800819],
       [0.72598449, 0.29514081, 0.19521257],
       [0.54928349, 0.14095439, 0.77200708],
       [0.98121694, 0.48638789, 0.17133006]])

Note that the official NumPy states that `np.random.rand` "is a convenience function. If you want an interface that
takes a shape-tuple as the first argument, refer to `np.random.random_sample`."

Most NumPy methods now take a shape-tuple as the first argument. The reason for the discrepancy in `np.random.rand`'s API could be of historical origin. Some people believe that it is to make the API more familiar to Matlab users, while others believe it is a result of merging different libraries of different syntaxes when creating NumPy.

For a more consistent API, it is recommended to use `np.random.random` instead of `np.random.rand`.

In [42]:
np.random.random((5, 3))

array([[0.1627072 , 0.05863506, 0.0599153 ],
       [0.45304188, 0.85003114, 0.83917487],
       [0.17636866, 0.47912759, 0.21039306],
       [0.36664584, 0.45587276, 0.01978475],
       [0.10482004, 0.53958522, 0.19078593]])

Construct a matrix filled zeros and of dtype long:



In [43]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [44]:
np.zeros((5, 3), dtype=np.long)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Construct a tensor directly from data:



In [45]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [46]:
a = np.array([5.5, 3])
print(repr(a))

array([5.5, 3. ])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [47]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7226,  0.7050, -0.1223],
        [-0.0823,  0.1507, -1.6925],
        [ 0.7180, -1.0116,  0.3251],
        [ 2.5652,  0.1425,  1.0602],
        [-0.7888,  0.7676, -1.6610]])


Due to my limited knowledge, I could not find their direct counterparts in NumPy. Here are the closest ones I can think of

In [54]:
a = np.ones((5, 3), dtype=np.double)
print(repr(a))

a = np.random.standard_normal(y.shape).astype(np.float)
print(repr(a))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
array([[ 1.2226522 ,  0.4654828 , -1.52909148],
       [ 1.07474797, -0.97334343,  1.38093876],
       [-0.96374385,  0.36087359, -0.11050262],
       [-0.1996    ,  0.54720236, -0.20798344],
       [-1.23443732,  0.13209339, -2.01319573]])


Get its size:



In [55]:
print(x.size())

torch.Size([5, 3])


In [56]:
a.shape

(5, 3)

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [57]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1143,  1.5666,  0.1114],
        [ 0.1479,  0.8518, -0.9449],
        [ 1.6502, -0.9304,  1.1491],
        [ 2.7745,  0.2022,  1.3719],
        [-0.7872,  1.4197, -0.9144]])


In [59]:
b = np.random.random((5, 3))
a + b

array([[ 1.94985743,  0.95451481, -0.73717511],
       [ 1.5532944 , -0.1132972 ,  1.39630206],
       [-0.45545447,  0.93046737,  0.07407713],
       [-0.09962069,  0.65958183,  0.76538712],
       [-1.14032461,  0.31929953, -1.62938092]])

Addition: syntax 2



In [60]:
print(torch.add(x, y))

tensor([[-0.1143,  1.5666,  0.1114],
        [ 0.1479,  0.8518, -0.9449],
        [ 1.6502, -0.9304,  1.1491],
        [ 2.7745,  0.2022,  1.3719],
        [-0.7872,  1.4197, -0.9144]])


In [61]:
np.add(a, b)

array([[ 1.94985743,  0.95451481, -0.73717511],
       [ 1.5532944 , -0.1132972 ,  1.39630206],
       [-0.45545447,  0.93046737,  0.07407713],
       [-0.09962069,  0.65958183,  0.76538712],
       [-1.14032461,  0.31929953, -1.62938092]])

Addition: providing an output tensor as argument



In [62]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1143,  1.5666,  0.1114],
        [ 0.1479,  0.8518, -0.9449],
        [ 1.6502, -0.9304,  1.1491],
        [ 2.7745,  0.2022,  1.3719],
        [-0.7872,  1.4197, -0.9144]])


In [63]:
result_2 = np.empty((5, 3))

In [65]:
np.add(a, b, out=result_2)
result_2

array([[ 1.94985743,  0.95451481, -0.73717511],
       [ 1.5532944 , -0.1132972 ,  1.39630206],
       [-0.45545447,  0.93046737,  0.07407713],
       [-0.09962069,  0.65958183,  0.76538712],
       [-1.14032461,  0.31929953, -1.62938092]])

Addition: in-place



In [66]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.1143,  1.5666,  0.1114],
        [ 0.1479,  0.8518, -0.9449],
        [ 1.6502, -0.9304,  1.1491],
        [ 2.7745,  0.2022,  1.3719],
        [-0.7872,  1.4197, -0.9144]])


In [80]:
np.add(a, b, out=b)

array([[ 3.17250963,  1.41999761, -2.26626659],
       [ 2.62804237, -1.08664063,  2.77724082],
       [-1.41919832,  1.29134097, -0.03642549],
       [-0.29922069,  1.2067842 ,  0.55740367],
       [-2.37476193,  0.45139292, -3.64257665]])

In [81]:
b

array([[ 3.17250963,  1.41999761, -2.26626659],
       [ 2.62804237, -1.08664063,  2.77724082],
       [-1.41919832,  1.29134097, -0.03642549],
       [-0.29922069,  1.2067842 ,  0.55740367],
       [-2.37476193,  0.45139292, -3.64257665]])

<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [82]:
print(x[:, 1])

tensor([ 0.7050,  0.1507, -1.0116,  0.1425,  0.7676])


In [83]:
a[:, 1]

array([ 0.4654828 , -0.97334343,  0.36087359,  0.54720236,  0.13209339])

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``.

WARNING: Be very careful, NumPy users! Here `torch.view` is essentially `np.reshape` and is completely different from `np.view`.

In [95]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [99]:
a = np.random.standard_normal((4, 4))
b = a.reshape(16)
c = a.reshape(-1, 8)
print(a.shape, b.shape, c.shape)

(4, 4) (16,) (2, 8)


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [100]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3098])
0.3097800612449646


In [110]:
a = np.random.standard_normal(1)
print(a)
print(a.item())

[-0.71335854]
-0.7133585385709382


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [111]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [112]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [113]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [114]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [116]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!